name: CI

on:
  push:
    branches:
      - master
    tags: '*'
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        architecture: [x64]
        python-version: ['3.8']
        julia-version: ['1']
      fail-fast: false
    name: Test ${{ matrix.os }} ${{ matrix.architecture }}
      Julia ${{ matrix.julia-version }}
      Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v1
      - name: Setup julia
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.architecture }}
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.architecture }}
      - name: Install tox
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade tox
      - name: Run test
        run: python -m tox -- --cov=julia
        env:
          CI: 'true'  # run tests marked by @only_in_ci
          TOXENV: py
          PYJULIA_TEST_REBUILD: 'yes'
      - run: cat .tox/py/log/pytest.log
        if: always()
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
          name: codecov-umbrella
